env:
  global:
  - GIT_NAME: "'Markdown autodeploy'"
  - GIT_EMAIL: djw8605@gmail.com
  - GH_REF: git@github.com:unlhcc/hccgo-dev.git
  - GH_HTTP: https://github.com/unlhcc/hccgo-dev.git
  - CXX=g++-4.8
language: node_js
node_js:
  - "node"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  
script:
- ./test/run_tests.sh

